#!/bin/bash
set -e

case "$1" in
purge)
	rm -rf /var/lib/distiller-platform-update
	rm -rf /var/log/distiller-platform-update

	echo "distiller-platform-update purged successfully."
	;;

remove | upgrade | failed-upgrade | abort-install | abort-upgrade | disappear) ;;

*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
